# Generated by Django 6.0.5 on 2026-05-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
