# Generated by Django 6.0.5 on 2026-05-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
